package format

import (
	"io"
	"strings"
	"text/template"
	"time"
)

const siteURL = "https://dvhthomas.github.io/gh-velocity/"

// MetricRow is a single row in the metrics table.
type MetricRow struct {
	Name  string
	Value string
}

// DetailSection is an optional sub-table (e.g., "Closed Issues", "Linked PRs").
type DetailSection struct {
	Title   string
	Headers []string   // column headers
	Rows    [][]string // each row has len(Headers) cells
}

// DetailData is the input to the shared detail markdown template.
type DetailData struct {
	Facts    string          // "opened 2026-03-20 · closed 2026-03-20" etc.
	Metrics  []MetricRow     // rows for the metrics table
	Sections []DetailSection // optional sub-tables
}

var templateFuncs = template.FuncMap{
	"join": strings.Join,
	"dashes": func(headers []string) string {
		parts := make([]string, len(headers))
		for i := range headers {
			parts[i] = "---"
		}
		return strings.Join(parts, " | ")
	},
	"row": func(cells []string) string {
		return strings.Join(cells, " | ")
	},
}

var detailTemplate = template.Must(template.New("detail").Funcs(templateFuncs).Parse(
	`### Metrics

{{ .Facts }}

| Metric | Value |
|--------|-------|
{{ range .Metrics -}}
| {{ .Name }} | {{ .Value }} |
{{ end }}
{{- range .Sections }}
### {{ .Title }}

| {{ join .Headers " | " }} |
| {{ dashes .Headers }} |
{{ range .Rows -}}
| {{ row . }} |
{{ end }}
{{- end }}
<sub>Generated by <a href="` + siteURL + `">gh-velocity</a></sub>
`))

// WriteDetail renders the shared detail markdown template.
func WriteDetail(w io.Writer, d DetailData) error {
	return detailTemplate.Execute(w, d)
}

// FormatFacts joins non-empty fact strings with " · ".
func FormatFacts(facts ...string) string {
	var out []string
	for _, f := range facts {
		if f != "" {
			out = append(out, f)
		}
	}
	return strings.Join(out, " · ")
}

// FormatTimeFact formats a labeled timestamp for the facts line.
func FormatTimeFact(label string, t time.Time) string {
	return label + " " + t.UTC().Format("2006-01-02 15:04") + " UTC"
}
