package format

import (
	"io"
	"strings"
	"text/template"
	"time"
)

// DocPaths for linking from metric status values.
const (
	DocPathCycleTimeSetup = "/guides/cycle-time-setup/"
	DocPathCycleTimeNA    = "/guides/troubleshooting/#cycle-time-shows-na-for-all-issues"
)

// Metric status constants — drive rendering in template and JSON.
const (
	StatusOK            = "ok"
	StatusNA            = "na"            // data not available for this item
	StatusNotConfigured = "not_configured" // feature needs setup
)

// MetricRow is a single row in the metrics table.
type MetricRow struct {
	Name    string
	Value   string // display value when Status is StatusOK
	Status  string // StatusOK, StatusNA, StatusNotConfigured
	HelpURL string // docs link when Status is StatusNotConfigured
}

// DetailSection is an optional sub-table (e.g., "Closed Issues", "Linked PRs").
type DetailSection struct {
	Title   string
	Headers []string   // column headers
	Rows    [][]string // each row has len(Headers) cells
}

// DetailLink is a markdown link for use in template rendering.
type DetailLink struct {
	Text string // e.g., "#84"
	URL  string // full URL
}

// DetailData is the input to the shared detail markdown template.
type DetailData struct {
	Facts        string          // "opened 2026-03-20 · closed 2026-03-20" etc.
	Metrics      []MetricRow     // rows for the metrics table
	ClosedIssues []DetailLink    // linked issues (rendered as inline sentence)
	Sections     []DetailSection // optional sub-tables
}

var templateFuncs = template.FuncMap{
	"join": strings.Join,
	"isOK":            func() string { return StatusOK },
	"isNA":            func() string { return StatusNA },
	"isNotConfigured": func() string { return StatusNotConfigured },
	"plural": func(n int, singular, plural string) string {
		if n == 1 {
			return singular
		}
		return plural
	},
	"dashes": func(headers []string) string {
		parts := make([]string, len(headers))
		for i := range headers {
			parts[i] = "---"
		}
		return strings.Join(parts, " | ")
	},
	"row": func(cells []string) string {
		return strings.Join(cells, " | ")
	},
}

var detailTemplate = template.Must(template.New("detail").Funcs(templateFuncs).Parse(
	`### Metrics

{{ .Facts }}{{ if .ClosedIssues }} · closed {{ plural (len .ClosedIssues) "issue" "issues" }}:{{ range .ClosedIssues }} [{{ .Text }}]({{ .URL }}){{ end }}{{ end }}

| Metric | Value |
|--------|-------|
{{ range .Metrics -}}
{{- if eq .Status (isNotConfigured) -}}
| {{ .Name }} | [not configured]({{ .HelpURL }}) |
{{ else if eq .Status (isNA) -}}
| {{ .Name }} | [n/a]({{ .HelpURL }}) |
{{ else -}}
| {{ .Name }} | {{ .Value }} |
{{ end -}}
{{- end }}
{{- range .Sections }}
### {{ .Title }}

| {{ join .Headers " | " }} |
| {{ dashes .Headers }} |
{{ range .Rows -}}
| {{ row . }} |
{{ end }}
{{- end }}
<sub>Generated by <a href="` + DocSiteURL + `/">gh-velocity</a></sub>
`))

// WriteDetail renders the shared detail markdown template.
func WriteDetail(w io.Writer, d DetailData) error {
	return detailTemplate.Execute(w, d)
}

// FormatFacts joins non-empty fact strings with " · ".
func FormatFacts(facts ...string) string {
	var out []string
	for _, f := range facts {
		if f != "" {
			out = append(out, f)
		}
	}
	return strings.Join(out, " · ")
}

// FormatTimeFact formats a labeled timestamp for the facts line.
func FormatTimeFact(label string, t time.Time) string {
	return label + " " + t.UTC().Format("2006-01-02 15:04") + " UTC"
}
